name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: leafy-momentum-456920-p2
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          IMAGE="us-central1-docker.pkg.dev/leafy-momentum-456920-p2/todolist/todo-list-app:$GITHUB_SHA"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy todo-list-app \
            --image=us-central1-docker.pkg.dev/leafy-momentum-456920-p2/todolist/todo-list-app:$GITHUB_SHA \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --memory=512Mi
